import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  jsonb,
  pgEnum,
  integer,
} from "drizzle-orm/pg-core";

// Enums
export const userRoleEnum = pgEnum("user_role", ["instructor", "member"]);

// ===== users 테이블 =====
export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: varchar("email", { length: 255 }).unique().notNull(),
  passwordHash: text("password_hash").notNull(),
  role: userRoleEnum("role").notNull().default("member"),
  name: varchar("name", { length: 100 }).notNull(),
  pushToken: text("push_token"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ===== members 테이블 =====
export const members = pgTable("members", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .references(() => users.id),
  name: text("name").notNull(),
  phone: text("phone"),
  dateOfBirth: text("date_of_birth"),
  bodyConditions: jsonb("body_conditions").default([]),
  exercisePreferences: jsonb("exercise_preferences").default({}),
  fitnessLevel: text("fitness_level").notNull().default("beginner"),
  notes: text("notes"),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ===== weeklySchedules 테이블 =====
export const weeklySchedules = pgTable("weekly_schedules", {
  id: uuid("id").defaultRandom().primaryKey(),
  memberId: uuid("member_id")
    .references(() => members.id)
    .notNull(),
  instructorId: uuid("instructor_id")
    .references(() => users.id)
    .notNull(),
  dayOfWeek: integer("day_of_week").notNull(), // 0=일~6=토
  startTime: text("start_time").notNull(), // 예: "10:00"
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ===== sessions 테이블 =====
export const sessions = pgTable("sessions", {
  id: uuid("id").defaultRandom().primaryKey(),
  memberId: uuid("member_id")
    .references(() => members.id)
    .notNull(),
  instructorId: uuid("instructor_id")
    .references(() => users.id),
  date: text("date").notNull(), // 예: "2026-03-20"
  conditionAiRaw: jsonb("condition_ai_raw"),
  conditionFinal: jsonb("condition_final"),
  conditionCheckedAt: text("condition_checked_at"),
  memberNote: text("member_note"),
  requestedCategories: jsonb("requested_categories").default([]),
  isAutoGenerated: boolean("is_auto_generated").default(false),
  status: text("status").notNull().default("pending"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
