import "dotenv/config";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { exerciseCatalog } from "./schema";
import { sql } from "drizzle-orm";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

const client = postgres(databaseUrl);
const db = drizzle(client);

const exercises = [
  // ========================================
  // ===== CORE (30개) =====
  // ========================================
  {
    name: "The Hundred",
    nameKo: "헌드레드",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors"],
    contraindications: ["목디스크"],
    durationSeconds: 120,
    description: "팔을 펌핑하며 코어를 활성화하는 필라테스 대표 동작입니다.",
  },
  {
    name: "Roll Up",
    nameKo: "롤업",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "spine_extensors"],
    contraindications: ["허리디스크", "측만증"],
    durationSeconds: 90,
    description: "누운 상태에서 척추를 하나씩 들어올리며 일어나는 동작입니다.",
  },
  {
    name: "Single Leg Stretch",
    nameKo: "싱글 레그 스트레치",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "한쪽 다리를 번갈아 당기며 코어를 강화합니다.",
  },
  {
    name: "Double Leg Stretch",
    nameKo: "더블 레그 스트레치",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "transverse_abs"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "양 팔다리를 동시에 뻗으며 코어 안정성을 높입니다.",
  },
  {
    name: "Criss-Cross",
    nameKo: "크리스크로스",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "abs"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "상체를 회전하며 복사근을 강화합니다.",
  },
  {
    name: "Plank",
    nameKo: "플랭크",
    category: "core",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["transverse_abs", "shoulders", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "전신의 코어 근육을 동시에 활성화하는 기본 동작입니다.",
  },
  {
    name: "Dead Bug",
    nameKo: "데드버그",
    category: "core",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "누운 상태에서 팔다리를 교차로 움직이며 코어를 안정화합니다.",
  },
  {
    name: "Bicycle",
    nameKo: "바이시클",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "obliques", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "자전거 페달을 밟는 동작으로 복근 전체를 활성화합니다.",
  },
  {
    name: "Teaser",
    nameKo: "티저",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "spine_extensors"],
    contraindications: ["허리디스크", "목디스크", "측만증"],
    durationSeconds: 90,
    description: "V자 균형을 잡으며 전신 코어를 강화하는 고급 동작입니다.",
  },
  // 추가 21개
  {
    name: "Roll Over",
    nameKo: "롤 오버",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "spine_extensors"],
    contraindications: ["허리디스크", "목디스크", "고혈압"],
    durationSeconds: 90,
    description: "다리를 머리 위로 넘기며 척추 분절과 코어를 강화합니다.",
  },
  {
    name: "Scissors",
    nameKo: "시저스",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "hamstrings"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "누워서 다리를 가위처럼 교차하며 복근을 강화합니다.",
  },
  {
    name: "Double Straight Leg Lower",
    nameKo: "더블 스트레이트 레그 로워",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "transverse_abs"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "양 다리를 펴고 내리며 하복부를 집중 강화합니다.",
  },
  {
    name: "Teaser II",
    nameKo: "티저 II",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "spine_extensors"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 90,
    description: "팔을 뻗은 상태에서 다리를 올리는 고급 티저 변형입니다.",
  },
  {
    name: "Teaser III",
    nameKo: "티저 III",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "spine_extensors"],
    contraindications: ["허리디스크", "목디스크", "측만증"],
    durationSeconds: 90,
    description: "팔다리를 동시에 올리고 내리는 최고 난이도 티저입니다.",
  },
  {
    name: "Corkscrew",
    nameKo: "코르크스크류",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "obliques", "hip_flexors"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 60,
    description: "다리로 큰 원을 그리며 깊은 코어와 복사근을 강화합니다.",
  },
  {
    name: "Hip Circles",
    nameKo: "힙 서클",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "obliques", "hip_flexors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉아서 다리로 원을 그리며 코어 전체를 강화합니다.",
  },
  {
    name: "Jackknife",
    nameKo: "잭나이프",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "spine_extensors", "hip_flexors"],
    contraindications: ["허리디스크", "목디스크", "고혈압"],
    durationSeconds: 60,
    description: "다리를 수직으로 올리며 강한 코어 안정성을 요구하는 동작입니다.",
  },
  {
    name: "Control Balance",
    nameKo: "컨트롤 밸런스",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hamstrings", "spine_extensors"],
    contraindications: ["허리디스크", "목디스크", "고혈압"],
    durationSeconds: 60,
    description: "어깨 위에서 균형을 잡으며 한 다리씩 올리는 고급 동작입니다.",
  },
  {
    name: "Side Plank",
    nameKo: "사이드 플랭크",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "shoulders", "transverse_abs"],
    contraindications: ["손목터널증후군", "어깨부상"],
    durationSeconds: 45,
    description: "옆으로 몸을 지탱하며 측면 코어를 강화합니다.",
  },
  {
    name: "Bird Dog",
    nameKo: "버드독",
    category: "core",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["transverse_abs", "spine_extensors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "네발 기기 자세에서 반대쪽 팔다리를 들어 균형을 잡습니다.",
  },
  {
    name: "Oblique Roll Back",
    nameKo: "오블리크 롤백",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "abs", "hip_flexors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "회전을 추가한 롤백으로 복사근을 집중 강화합니다.",
  },
  {
    name: "Short Spine Massage",
    nameKo: "숏 스파인 마사지",
    category: "core",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "spine_extensors", "hamstrings"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 90,
    description: "리포머에서 척추를 분절하며 코어와 유연성을 동시에 개선합니다.",
  },
  {
    name: "Long Spine Massage",
    nameKo: "롱 스파인 마사지",
    category: "core",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["abs", "spine_extensors", "hamstrings"],
    contraindications: ["허리디스크", "목디스크", "고혈압"],
    durationSeconds: 90,
    description: "리포머에서 다리를 길게 뻗어 척추를 분절하는 고급 동작입니다.",
  },
  {
    name: "Knee Stretches Round Back",
    nameKo: "니 스트레치 라운드백",
    category: "core",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "transverse_abs", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 둥근 등으로 무릎을 당기며 코어를 강화합니다.",
  },
  {
    name: "Knee Stretches Knees Off",
    nameKo: "니 스트레치 니즈오프",
    category: "core",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["abs", "transverse_abs", "hip_flexors", "shoulders"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "무릎을 떼고 수행하는 고급 니 스트레치로 코어를 극대화합니다.",
  },
  {
    name: "Stomach Massage Round",
    nameKo: "스토마치 마사지 라운드",
    category: "core",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "transverse_abs", "quads"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "리포머에서 둥근 등 자세로 다리를 밀며 코어를 활성화합니다.",
  },
  {
    name: "Stomach Massage Flat",
    nameKo: "스토마치 마사지 플랫",
    category: "core",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "spine_extensors", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 편 등 자세로 다리를 밀며 자세와 코어를 동시에 강화합니다.",
  },
  {
    name: "Coordination",
    nameKo: "코디네이션",
    category: "core",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "hip_flexors", "triceps"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "리포머에서 팔다리를 동시에 움직이며 코어 협응력을 높입니다.",
  },
  {
    name: "Ab Curl on Ball",
    nameKo: "볼 복근 컬",
    category: "core",
    difficulty: "beginner",
    equipment: "ball",
    muscleGroups: ["abs", "transverse_abs"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "짐볼 위에서 복근 컬을 수행하여 불안정한 면에서 코어를 강화합니다.",
  },
  {
    name: "Oblique Curl on Ball",
    nameKo: "볼 사선 컬",
    category: "core",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["obliques", "abs"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "짐볼 위에서 사선으로 컬하여 복사근을 집중 강화합니다.",
  },

  // ========================================
  // ===== LOWER BODY (30개) =====
  // ========================================
  {
    name: "Bridge",
    nameKo: "브릿지",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "엉덩이를 들어올리며 둔근과 코어를 강화합니다.",
  },
  {
    name: "Leg Circle",
    nameKo: "레그 서클",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "quads", "adductors"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 다리로 원을 그리며 고관절을 강화합니다.",
  },
  {
    name: "Footwork on Reformer",
    nameKo: "리포머 풋워크",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 90,
    description: "리포머에서 다리 근력과 정렬을 개선합니다.",
  },
  {
    name: "Lunge with Ball",
    nameKo: "볼 런지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "볼을 이용한 런지로 하체 근력과 균형을 향상합니다.",
  },
  {
    name: "Side Leg Lift with Band",
    nameKo: "밴드 사이드 레그 리프트",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["abductors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "밴드 저항을 이용해 외전근과 둔근을 강화합니다.",
  },
  {
    name: "Calf Raise on Chair",
    nameKo: "체어 카프 레이즈",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "chair",
    muscleGroups: ["calves", "quads"],
    contraindications: [],
    durationSeconds: 45,
    description: "필라테스 체어에서 종아리를 강화합니다.",
  },
  {
    name: "Clamshell",
    nameKo: "클램셸",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abductors", "glutes"],
    contraindications: [],
    durationSeconds: 45,
    description: "옆으로 누워 무릎을 열고 닫으며 둔근을 활성화합니다.",
  },
  // 추가 23개
  {
    name: "Single Leg Circle",
    nameKo: "싱글 레그 서클",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "adductors", "abductors"],
    contraindications: [],
    durationSeconds: 60,
    description: "한 다리로 원을 그리며 고관절 안정성을 높입니다.",
  },
  {
    name: "Side Kick Front Back",
    nameKo: "사이드 킥 프론트백",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "glutes", "hamstrings"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 누워 다리를 앞뒤로 차며 고관절을 강화합니다.",
  },
  {
    name: "Side Kick Up Down",
    nameKo: "사이드 킥 업다운",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abductors", "adductors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 누워 다리를 위아래로 차며 외전근을 강화합니다.",
  },
  {
    name: "Side Kick Small Circles",
    nameKo: "사이드 킥 스몰 서클",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abductors", "glutes", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 누워 다리로 작은 원을 그리며 고관절을 안정화합니다.",
  },
  {
    name: "Side Kick Inner Thigh",
    nameKo: "사이드 킥 이너 타이",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["adductors", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 누워 아래 다리를 올리며 내전근을 강화합니다.",
  },
  {
    name: "Side Kick Bicycle",
    nameKo: "사이드 킥 바이시클",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "glutes", "quads", "hamstrings"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 누워 자전거 동작으로 고관절 가동범위를 넓힙니다.",
  },
  {
    name: "Side Kick Kneeling",
    nameKo: "사이드 킥 닐링",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abductors", "glutes", "obliques"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "무릎을 꿇고 옆으로 다리를 차며 균형과 하체를 강화합니다.",
  },
  {
    name: "Shoulder Bridge",
    nameKo: "숄더 브릿지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "브릿지 자세에서 한 다리를 올려 둔근을 집중 강화합니다.",
  },
  {
    name: "Shoulder Bridge Single Leg",
    nameKo: "숄더 브릿지 싱글레그",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "한 다리로 브릿지를 유지하며 둔근과 코어를 강화합니다.",
  },
  {
    name: "Leg Pull Front",
    nameKo: "레그 풀 프론트",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "calves", "shoulders"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "플랭크 자세에서 한 다리를 들어올리며 하체와 코어를 강화합니다.",
  },
  {
    name: "Leg Pull Back",
    nameKo: "레그 풀 백",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "triceps"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "역 플랭크에서 한 다리를 들어올리며 후면 하체를 강화합니다.",
  },
  {
    name: "Standing Side Splits",
    nameKo: "스탠딩 사이드 스플릿",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["adductors", "abductors", "glutes"],
    contraindications: ["고관절부상"],
    durationSeconds: 60,
    description: "리포머에서 서서 다리를 벌리며 내전근과 외전근을 강화합니다.",
  },
  {
    name: "Front Splits",
    nameKo: "프론트 스플릿",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["hip_flexors", "hamstrings", "quads"],
    contraindications: ["고관절부상"],
    durationSeconds: 60,
    description: "리포머에서 런지 자세로 고관절 유연성과 근력을 동시에 강화합니다.",
  },
  {
    name: "Back Splits",
    nameKo: "백 스플릿",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "glutes", "hip_flexors"],
    contraindications: ["고관절부상"],
    durationSeconds: 60,
    description: "리포머에서 뒤로 런지하며 후면 하체를 강화합니다.",
  },
  {
    name: "Eve's Lunge",
    nameKo: "이브스 런지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hip_flexors", "quads", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 런지하며 고관절 유연성과 하체 근력을 키웁니다.",
  },
  {
    name: "Standing Lunge on Chair",
    nameKo: "체어 스탠딩 런지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어에서 런지 동작으로 하체를 강화합니다.",
  },
  {
    name: "Going Up Front",
    nameKo: "고잉 업 프론트",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어에 한 발을 올리고 일어서며 하체 근력을 강화합니다.",
  },
  {
    name: "Going Up Side",
    nameKo: "고잉 업 사이드",
    category: "lower_body",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["abductors", "glutes", "quads"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어 옆에서 한 발로 올라서며 외전근과 둔근을 강화합니다.",
  },
  {
    name: "Frog on Reformer",
    nameKo: "리포머 프로그",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["adductors", "quads", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 개구리 자세로 다리를 뻗으며 내전근을 강화합니다.",
  },
  {
    name: "Leg Circles on Reformer",
    nameKo: "리포머 레그 서클",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hip_flexors", "adductors", "abductors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머 스트랩에 발을 걸고 원을 그리며 고관절을 강화합니다.",
  },
  {
    name: "Running on Reformer",
    nameKo: "리포머 러닝",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["calves", "quads", "hamstrings"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 달리기 동작으로 종아리와 하체를 강화합니다.",
  },
  {
    name: "Pelvic Lift on Reformer",
    nameKo: "리포머 펠빅 리프트",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["glutes", "hamstrings", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 골반을 들어올리며 둔근과 코어를 강화합니다.",
  },
  {
    name: "Hamstring Curl on Ball",
    nameKo: "볼 햄스트링 컬",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["hamstrings", "glutes", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "짐볼 위에 발을 올리고 당기며 햄스트링을 강화합니다.",
  },

  // ========================================
  // ===== STRENGTH (25개) =====
  // ========================================
  {
    name: "Scapular Stabilization",
    nameKo: "견갑골 안정화",
    category: "strength",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["rhomboids", "serratus", "trapezius"],
    contraindications: [],
    durationSeconds: 45,
    description: "견갑골 주변 근육을 강화하여 어깨 안정성을 높입니다.",
  },
  {
    name: "Push Up Reformer",
    nameKo: "리포머 푸시업",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["chest", "triceps", "shoulders"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 푸시업하며 상체 근력을 강화합니다.",
  },
  {
    name: "Arm Circles with Band",
    nameKo: "밴드 팔 원 그리기",
    category: "strength",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["shoulders", "deltoids"],
    contraindications: ["어깨부상"],
    durationSeconds: 45,
    description: "밴드 저항을 이용해 어깨 안정성과 근력을 높입니다.",
  },
  {
    name: "Bicep Curl with Band",
    nameKo: "밴드 이두근 컬",
    category: "strength",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["biceps", "forearms"],
    contraindications: [],
    durationSeconds: 45,
    description: "밴드로 이두근을 강화하는 기본 운동입니다.",
  },
  {
    name: "Reformer Rowing",
    nameKo: "리포머 로잉",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "rhomboids", "biceps"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 로잉하며 등과 팔 근력을 강화합니다.",
  },
  {
    name: "Chest Press Reformer",
    nameKo: "리포머 체스트 프레스",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["chest", "triceps", "shoulders"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "리포머에서 가슴을 밀며 상체 근력을 강화합니다.",
  },
  {
    name: "Scooter",
    nameKo: "스쿠터",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["glutes", "hamstrings", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 한 다리로 밀며 둔근과 하체를 강화합니다.",
  },
  // 추가 18개
  {
    name: "Footwork Parallel",
    nameKo: "풋워크 패럴렐",
    category: "strength",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 발을 나란히 놓고 밀며 하체 전체를 강화합니다.",
  },
  {
    name: "Footwork V Position",
    nameKo: "풋워크 V 포지션",
    category: "strength",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["quads", "adductors", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "V자 발 자세로 풋워크하며 내전근을 집중 강화합니다.",
  },
  {
    name: "Footwork Wide V",
    nameKo: "풋워크 와이드 V",
    category: "strength",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["quads", "abductors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "넓은 V자 발 자세로 풋워크하며 외전근을 강화합니다.",
  },
  {
    name: "Footwork Heels",
    nameKo: "풋워크 힐즈",
    category: "strength",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "발뒤꿈치로 풋워크하며 후면 하체를 강화합니다.",
  },
  {
    name: "Footwork on Chair",
    nameKo: "체어 풋워크",
    category: "strength",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "체어에서 풋워크하며 하체 근력과 안정성을 강화합니다.",
  },
  {
    name: "Leg Press on Chair",
    nameKo: "체어 레그 프레스",
    category: "strength",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어에서 페달을 밀며 하체 전체 근력을 강화합니다.",
  },
  {
    name: "Standing Leg Press",
    nameKo: "스탠딩 레그 프레스",
    category: "strength",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "체어에서 서서 페달을 밟으며 하체를 강화합니다.",
  },
  {
    name: "Arm Springs Bicep Curl",
    nameKo: "암 스프링 이두근 컬",
    category: "strength",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["biceps", "shoulders"],
    contraindications: [],
    durationSeconds: 45,
    description: "캐딜락 스프링으로 이두근을 집중 강화합니다.",
  },
  {
    name: "Arm Springs Tricep Press",
    nameKo: "암 스프링 삼두근 프레스",
    category: "strength",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["triceps", "shoulders"],
    contraindications: [],
    durationSeconds: 45,
    description: "캐딜락 스프링으로 삼두근을 집중 강화합니다.",
  },
  {
    name: "Arm Springs Chest Expansion",
    nameKo: "암 스프링 체스트 익스팬션",
    category: "strength",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["chest", "shoulders", "lats"],
    contraindications: [],
    durationSeconds: 60,
    description: "캐딜락 스프링으로 가슴을 열고 등을 강화합니다.",
  },
  {
    name: "Pulling Straps",
    nameKo: "풀링 스트랩",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "rhomboids", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에 엎드려 스트랩을 당기며 등 근력을 강화합니다.",
  },
  {
    name: "Pulling Straps T",
    nameKo: "풀링 스트랩 T",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["rhomboids", "deltoids", "trapezius"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "T자로 팔을 벌리며 스트랩을 당겨 상부 등을 강화합니다.",
  },
  {
    name: "Long Box Pull",
    nameKo: "롱박스 풀",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "biceps", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "롱박스에 엎드려 당기며 등과 팔을 강화합니다.",
  },
  {
    name: "Push Through Front",
    nameKo: "푸시 스루 프론트",
    category: "strength",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["shoulders", "chest", "abs"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "캐딜락 바를 앞으로 밀며 어깨와 코어를 강화합니다.",
  },
  {
    name: "Push Through Back",
    nameKo: "푸시 스루 백",
    category: "strength",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["lats", "triceps", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "캐딜락 바를 뒤로 밀며 등과 삼두근을 강화합니다.",
  },
  {
    name: "Rowing Front",
    nameKo: "로잉 프론트",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "shoulders", "biceps"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에 앉아 앞에서 당기며 코어와 상체를 강화합니다.",
  },
  {
    name: "Rowing Back",
    nameKo: "로잉 백",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "rhomboids", "triceps"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에 앉아 뒤에서 당기며 등과 삼두근을 강화합니다.",
  },
  {
    name: "Pilates Push Up",
    nameKo: "필라테스 푸시업",
    category: "strength",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["chest", "triceps", "shoulders", "abs"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "롤다운 후 워킹아웃하여 푸시업하는 필라테스 전신 동작입니다.",
  },

  // ========================================
  // ===== FLEXIBILITY (25개) =====
  // ========================================
  {
    name: "Spine Twist",
    nameKo: "스파인 트위스트",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 상체를 회전하여 척추 유연성을 높입니다.",
  },
  {
    name: "Swan Prep",
    nameKo: "스완 프렙",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 가볍게 상체를 들어올리는 입문 동작입니다.",
  },
  {
    name: "Swan Dive",
    nameKo: "스완 다이브",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크", "척추분리증", "측만증"],
    durationSeconds: 60,
    description: "엎드려 상체를 들어올리며 척추 신전 유연성을 높입니다.",
  },
  {
    name: "Spine Stretch Forward",
    nameKo: "스파인 스트레치 포워드",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hamstrings", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 척추를 앞으로 둥글게 말아 스트레칭합니다.",
  },
  {
    name: "Hip Flexor Stretch",
    nameKo: "고관절 굴곡근 스트레칭",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "고관절 앞쪽 근육을 늘여 유연성을 높입니다.",
  },
  // 추가 20개
  {
    name: "Saw",
    nameKo: "쏘우",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hamstrings", "obliques", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 회전하며 스트레칭하는 동작입니다.",
  },
  {
    name: "Open Leg Rocker",
    nameKo: "오픈 레그 로커",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["hamstrings", "abs", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "다리를 펴고 균형을 잡으며 구르는 고급 동작입니다.",
  },
  {
    name: "Seal",
    nameKo: "씰",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs", "hip_flexors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "발을 잡고 공처럼 굴러 척추를 마사지합니다.",
  },
  {
    name: "Rolling Like a Ball",
    nameKo: "롤링 라이크 어 볼",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "공처럼 구르며 척추 마사지 효과와 코어를 강화합니다.",
  },
  {
    name: "Boomerang",
    nameKo: "부메랑",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hamstrings", "spine_extensors", "shoulders"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 90,
    description: "구르고 균형을 잡는 복합 동작으로 전신 유연성을 키웁니다.",
  },
  {
    name: "Neck Roll",
    nameKo: "넥 롤",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "shoulders"],
    contraindications: ["목디스크"],
    durationSeconds: 45,
    description: "엎드려 스완 자세에서 목을 부드럽게 회전합니다.",
  },
  {
    name: "Roll Down on Tower",
    nameKo: "타워 롤다운",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "tower",
    muscleGroups: ["spine_extensors", "hamstrings", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "타워 바를 잡고 척추를 하나씩 말아내리며 유연성을 높입니다.",
  },
  {
    name: "Monkey",
    nameKo: "몽키",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "calves", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 깊이 쪼그려 앉으며 하체 유연성을 높입니다.",
  },
  {
    name: "Semi Circle",
    nameKo: "세미 서클",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["spine_extensors", "glutes", "hip_flexors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "리포머에서 반원을 그리며 척추 분절과 유연성을 키웁니다.",
  },
  {
    name: "Mermaid on Chair",
    nameKo: "체어 머메이드",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["obliques", "lats", "spine_extensors"],
    contraindications: ["측만증"],
    durationSeconds: 60,
    description: "체어에서 옆으로 늘이며 측면 유연성을 높입니다.",
  },
  {
    name: "Hip Flexor Stretch on Reformer",
    nameKo: "리포머 고관절 스트레칭",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["hip_flexors", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 런지 자세로 고관절 굴곡근을 깊이 스트레칭합니다.",
  },
  {
    name: "Snake Twist",
    nameKo: "스네이크 트위스트",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["obliques", "shoulders", "spine_extensors"],
    contraindications: ["허리디스크", "손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 몸을 비틀며 척추 회전 유연성을 높입니다.",
  },
  {
    name: "Crab",
    nameKo: "크랩",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs", "hip_flexors"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 60,
    description: "구르며 다리를 교차하는 고급 유연성 동작입니다.",
  },
  {
    name: "Rocking",
    nameKo: "로킹",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "quads", "shoulders"],
    contraindications: ["허리디스크", "척추분리증"],
    durationSeconds: 60,
    description: "엎드려 발을 잡고 앞뒤로 흔들며 전면 유연성을 높입니다.",
  },
  {
    name: "Hamstring Stretch on Cadillac",
    nameKo: "캐딜락 햄스트링 스트레칭",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "cadillac",
    muscleGroups: ["hamstrings", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "캐딜락 스프링으로 햄스트링을 안전하게 스트레칭합니다.",
  },
  {
    name: "Spine Corrector Stretch",
    nameKo: "스파인 코렉터 스트레칭",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "barrel",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "스파인 코렉터에 기대어 척추를 부드럽게 스트레칭합니다.",
  },
  {
    name: "Over the Barrel",
    nameKo: "오버 더 배럴",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["spine_extensors", "abs", "shoulders"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "배럴 위로 몸을 뒤로 넘기며 척추 신전 유연성을 높입니다.",
  },
  {
    name: "Side Bend on Barrel",
    nameKo: "배럴 사이드 벤드",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["obliques", "lats", "spine_extensors"],
    contraindications: ["측만증"],
    durationSeconds: 60,
    description: "배럴에서 옆으로 기대며 측면 유연성을 높입니다.",
  },
  {
    name: "Elephant",
    nameKo: "엘리펀트",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "calves", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 파이크 자세로 햄스트링 유연성을 높입니다.",
  },
  {
    name: "Cat Stretch",
    nameKo: "캣 스트레치",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: [],
    durationSeconds: 45,
    description: "네발 기기 자세에서 척추를 둥글게 말며 유연성을 높입니다.",
  },

  // ========================================
  // ===== POSTURE (25개) =====
  // ========================================
  {
    name: "Swan",
    nameKo: "스완",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 상체를 들어올리며 등 근육과 자세를 개선합니다.",
  },
  {
    name: "Swimming",
    nameKo: "스위밍",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 팔다리를 교차로 들어올리며 등 근육을 강화합니다.",
  },
  {
    name: "Breast Stroke Prep",
    nameKo: "브레스트 스트로크 프렙",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "rhomboids", "shoulders"],
    contraindications: [],
    durationSeconds: 60,
    description: "엎드려 팔을 당기며 상부 등 근육을 활성화합니다.",
  },
  {
    name: "Back Extension on Barrel",
    nameKo: "배럴 백 익스텐션",
    category: "posture",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["spine_extensors", "glutes"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "배럴 위에서 등을 펴며 척추 정렬을 개선합니다.",
  },
  {
    name: "Prone Scapular Squeeze",
    nameKo: "엎드린 견갑골 조이기",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["rhomboids", "trapezius", "spine_extensors"],
    contraindications: [],
    durationSeconds: 45,
    description: "엎드려 견갑골을 모으며 상부 등을 강화합니다.",
  },
  // 추가 20개
  {
    name: "Swan on Reformer",
    nameKo: "리포머 스완",
    category: "posture",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["spine_extensors", "shoulders", "glutes"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "리포머 박스에서 스완을 수행하며 자세를 개선합니다.",
  },
  {
    name: "Swan on Barrel",
    nameKo: "배럴 스완",
    category: "posture",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["spine_extensors", "glutes", "abs"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "배럴 위에서 스완하며 흉추 신전과 자세를 개선합니다.",
  },
  {
    name: "Single Leg Kick",
    nameKo: "싱글 레그 킥",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hamstrings", "spine_extensors", "glutes"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "엎드려 한쪽 무릎을 굽히며 등과 햄스트링을 강화합니다.",
  },
  {
    name: "Double Leg Kick",
    nameKo: "더블 레그 킥",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hamstrings", "spine_extensors", "shoulders"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "엎드려 양 무릎을 굽히고 상체를 들어올리며 자세를 개선합니다.",
  },
  {
    name: "Chest Expansion",
    nameKo: "체스트 익스팬션",
    category: "posture",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["chest", "shoulders", "rhomboids"],
    contraindications: [],
    durationSeconds: 45,
    description: "가슴을 열고 어깨를 뒤로 당기는 자세 교정 운동입니다.",
  },
  {
    name: "Pulling Straps Long Box",
    nameKo: "롱박스 풀링 스트랩",
    category: "posture",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "rhomboids", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "롱박스에서 스트랩을 당기며 등 근력과 자세를 개선합니다.",
  },
  {
    name: "Dart",
    nameKo: "다트",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "glutes", "rhomboids"],
    contraindications: [],
    durationSeconds: 45,
    description: "엎드려 팔을 뒤로 뻗고 상체를 들어올리며 등을 강화합니다.",
  },
  {
    name: "Cat-Cow",
    nameKo: "캣카우",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "네발 기기에서 척추를 굽히고 펴며 자세 인식을 높입니다.",
  },
  {
    name: "Back Extension on Cadillac",
    nameKo: "캐딜락 백 익스텐션",
    category: "posture",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["spine_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "캐딜락에서 등을 펴며 척추 정렬과 자세를 개선합니다.",
  },
  {
    name: "Prone Press Up",
    nameKo: "프론 프레스업",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "shoulders", "chest"],
    contraindications: ["허리디스크"],
    durationSeconds: 45,
    description: "엎드려 팔로 밀며 상체를 들어 흉추 신전을 유도합니다.",
  },
  {
    name: "Scapular Protraction Retraction",
    nameKo: "견갑골 전인 후인",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["serratus", "rhomboids", "trapezius"],
    contraindications: [],
    durationSeconds: 45,
    description: "견갑골을 앞뒤로 움직이며 어깨 안정성과 자세를 개선합니다.",
  },
  {
    name: "Chest Lift",
    nameKo: "체스트 리프트",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "spine_extensors"],
    contraindications: ["목디스크"],
    durationSeconds: 45,
    description: "누워서 상체를 살짝 들어올리며 복근과 자세를 개선합니다.",
  },
  {
    name: "Pelvic Clock",
    nameKo: "펠빅 클록",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "multifidus"],
    contraindications: [],
    durationSeconds: 60,
    description: "골반을 시계방향으로 움직이며 골반 정렬을 인식합니다.",
  },
  {
    name: "Wall Roll Down",
    nameKo: "월 롤다운",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "hamstrings", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "벽에 기대어 척추를 하나씩 말아내리며 자세를 교정합니다.",
  },
  {
    name: "Kneeling Arm Work",
    nameKo: "닐링 암 워크",
    category: "posture",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["shoulders", "rhomboids", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "무릎을 꿇고 팔 운동하며 자세와 상체를 동시에 강화합니다.",
  },
  {
    name: "T-Press on Reformer",
    nameKo: "리포머 T-프레스",
    category: "posture",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["rhomboids", "deltoids", "trapezius"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "리포머에서 T자 동작으로 상부 등과 자세를 개선합니다.",
  },
  {
    name: "Thoracic Extension on Roller",
    nameKo: "폼롤러 흉추 신전",
    category: "posture",
    difficulty: "beginner",
    equipment: "foam_roller",
    muscleGroups: ["spine_extensors", "chest"],
    contraindications: [],
    durationSeconds: 60,
    description: "폼롤러 위에서 흉추를 부드럽게 신전하여 자세를 개선합니다.",
  },
  {
    name: "Standing Roll Down",
    nameKo: "스탠딩 롤다운",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "hamstrings", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "서서 척추를 하나씩 말아내리며 척추 분절을 연습합니다.",
  },
  {
    name: "Grasshopper",
    nameKo: "그래스호퍼",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "glutes", "hamstrings"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 다리를 들어올리며 후면 체인을 강화합니다.",
  },
  {
    name: "Back Extension on Chair",
    nameKo: "체어 백 익스텐션",
    category: "posture",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["spine_extensors", "glutes"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "체어에서 등을 펴며 척추 정렬과 등 근력을 강화합니다.",
  },

  // ========================================
  // ===== STRETCHING (25개) =====
  // ========================================
  {
    name: "Cat-Cow Stretch",
    nameKo: "고양이-소 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "척추를 부드럽게 움직여 유연성을 향상시킵니다.",
  },
  {
    name: "Spine Stretch Forward Stretch",
    nameKo: "척추 전방 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "hamstrings"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 척추를 앞으로 둥글게 말아 스트레칭합니다.",
  },
  {
    name: "Hip Flexor Stretch Kneeling",
    nameKo: "무릎 꿇은 고관절 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "한쪽 무릎을 꿇고 고관절 앞쪽을 스트레칭합니다.",
  },
  {
    name: "Mermaid Stretch",
    nameKo: "인어 스트레칭",
    category: "stretching",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "lats", "spine_extensors"],
    contraindications: ["측만증"],
    durationSeconds: 60,
    description: "옆으로 몸을 길게 늘여 측면 근육을 이완합니다.",
  },
  {
    name: "Saw Stretch",
    nameKo: "쏘우 스트레칭",
    category: "stretching",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hamstrings", "obliques", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉아서 회전하며 스트레칭하는 복합 동작입니다.",
  },
  // 추가 20개
  {
    name: "Figure 4 Stretch",
    nameKo: "피겨 4 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["glutes", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 4자 모양으로 둔근을 스트레칭합니다.",
  },
  {
    name: "IT Band Stretch",
    nameKo: "장경인대 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abductors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "옆으로 다리를 꼬아 장경인대를 스트레칭합니다.",
  },
  {
    name: "Hamstring Stretch Supine",
    nameKo: "누운 햄스트링 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hamstrings", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 한 다리를 올려 햄스트링을 스트레칭합니다.",
  },
  {
    name: "Quad Stretch Side Lying",
    nameKo: "옆으로 누운 대퇴사두 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["quads", "hip_flexors"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "옆으로 누워 발을 잡고 대퇴사두근을 스트레칭합니다.",
  },
  {
    name: "Chest Opener on Barrel",
    nameKo: "배럴 체스트 오프너",
    category: "stretching",
    difficulty: "beginner",
    equipment: "barrel",
    muscleGroups: ["chest", "shoulders"],
    contraindications: [],
    durationSeconds: 60,
    description: "배럴 위에 기대어 가슴을 열어 스트레칭합니다.",
  },
  {
    name: "Lat Stretch on Reformer",
    nameKo: "리포머 광배근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["lats", "obliques"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 옆으로 늘이며 광배근을 스트레칭합니다.",
  },
  {
    name: "Standing Calf Stretch",
    nameKo: "서서 종아리 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["calves", "hamstrings"],
    contraindications: [],
    durationSeconds: 45,
    description: "벽을 짚고 서서 종아리를 깊이 스트레칭합니다.",
  },
  {
    name: "Spinal Rotation Stretch",
    nameKo: "척추 회전 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["obliques", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "누워서 무릎을 옆으로 넘기며 척추를 회전 스트레칭합니다.",
  },
  {
    name: "Child's Pose",
    nameKo: "차일드 포즈",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "lats", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "무릎을 꿇고 앞으로 엎드려 전신을 이완합니다.",
  },
  {
    name: "Shell Stretch",
    nameKo: "쉘 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "lats"],
    contraindications: [],
    durationSeconds: 60,
    description: "조개 모양으로 웅크려 허리와 등을 스트레칭합니다.",
  },
  {
    name: "Upper Trapezius Stretch",
    nameKo: "상부 승모근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["trapezius"],
    contraindications: [],
    durationSeconds: 45,
    description: "목을 옆으로 기울여 상부 승모근을 스트레칭합니다.",
  },
  {
    name: "Levator Scapulae Stretch",
    nameKo: "견갑거근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["trapezius", "rhomboids"],
    contraindications: [],
    durationSeconds: 45,
    description: "목을 대각선으로 숙여 견갑거근을 스트레칭합니다.",
  },
  {
    name: "Pec Stretch on Foam Roller",
    nameKo: "폼롤러 가슴 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "foam_roller",
    muscleGroups: ["chest", "shoulders"],
    contraindications: [],
    durationSeconds: 60,
    description: "폼롤러 위에 누워 팔을 벌려 가슴을 스트레칭합니다.",
  },
  {
    name: "Piriformis Stretch",
    nameKo: "이상근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["glutes", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 다리를 꼬아 이상근을 깊이 스트레칭합니다.",
  },
  {
    name: "Adductor Stretch",
    nameKo: "내전근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["adductors", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "앉아서 발바닥을 붙이고 내전근을 스트레칭합니다.",
  },
  {
    name: "TFL Stretch",
    nameKo: "대퇴근막장근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abductors", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "서서 다리를 교차하여 대퇴근막장근을 스트레칭합니다.",
  },
  {
    name: "Wrist Stretches",
    nameKo: "손목 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["forearms"],
    contraindications: [],
    durationSeconds: 45,
    description: "손목을 앞뒤로 굽혀 전완근을 스트레칭합니다.",
  },
  {
    name: "Side Stretch on Cadillac",
    nameKo: "캐딜락 사이드 스트레칭",
    category: "stretching",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["obliques", "lats"],
    contraindications: [],
    durationSeconds: 60,
    description: "캐딜락 바를 잡고 옆으로 늘이며 측면을 스트레칭합니다.",
  },
  {
    name: "Standing Hip Circle Stretch",
    nameKo: "서서 고관절 원 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "glutes", "adductors"],
    contraindications: [],
    durationSeconds: 60,
    description: "서서 고관절로 원을 그리며 관절 가동범위를 넓힙니다.",
  },
  {
    name: "Full Body Stretch",
    nameKo: "전신 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine_extensors", "shoulders", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 팔다리를 길게 뻗으며 전신을 이완합니다.",
  },

  // ========================================
  // ===== UPPER BODY (25개) =====
  // ========================================
  {
    name: "Push Up",
    nameKo: "푸시업",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["chest", "triceps", "shoulders", "abs"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "필라테스 스타일의 푸시업으로 상체와 코어를 함께 강화합니다.",
  },
  {
    name: "Arm Circles Upper Body",
    nameKo: "상체 팔 원 그리기",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["shoulders", "deltoids"],
    contraindications: ["어깨부상"],
    durationSeconds: 45,
    description: "밴드 저항으로 어깨 안정성과 가동범위를 개선합니다.",
  },
  {
    name: "Bicep Curl Upper Body",
    nameKo: "상체 이두근 컬",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["biceps", "forearms"],
    contraindications: [],
    durationSeconds: 45,
    description: "밴드로 이두근을 강화하는 상체 운동입니다.",
  },
  {
    name: "Scapular Stabilization Upper Body",
    nameKo: "상체 견갑골 안정화",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["rhomboids", "serratus", "trapezius"],
    contraindications: [],
    durationSeconds: 45,
    description: "견갑골 주변 근육을 강화하여 어깨 안정성을 높입니다.",
  },
  {
    name: "Tricep Press on Reformer",
    nameKo: "리포머 삼두근 프레스",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["triceps", "shoulders"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 삼두근을 집중 강화하는 운동입니다.",
  },
  // 추가 20개
  {
    name: "Hug a Tree",
    nameKo: "허그 어 트리",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["chest", "shoulders", "biceps"],
    contraindications: [],
    durationSeconds: 60,
    description: "나무를 안는 듯 팔을 모으며 가슴과 어깨를 강화합니다.",
  },
  {
    name: "Shaving",
    nameKo: "셰이빙",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["triceps", "shoulders"],
    contraindications: ["어깨부상"],
    durationSeconds: 45,
    description: "머리 뒤에서 팔을 위로 밀며 삼두근을 강화합니다.",
  },
  {
    name: "Serving",
    nameKo: "서빙",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["biceps", "shoulders", "abs"],
    contraindications: [],
    durationSeconds: 45,
    description: "접시를 내미는 듯한 동작으로 이두근과 코어를 강화합니다.",
  },
  {
    name: "Chest Fly on Reformer",
    nameKo: "리포머 체스트 플라이",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["chest", "shoulders"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "리포머에서 팔을 벌리고 모으며 가슴을 강화합니다.",
  },
  {
    name: "Reverse Fly on Reformer",
    nameKo: "리포머 리버스 플라이",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["rhomboids", "deltoids", "trapezius"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 팔을 뒤로 벌리며 상부 등을 강화합니다.",
  },
  {
    name: "Arm Springs All Directions",
    nameKo: "암 스프링 올 디렉션",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["shoulders", "biceps", "triceps", "chest"],
    contraindications: [],
    durationSeconds: 90,
    description: "캐딜락 스프링으로 여러 방향에서 팔 근력을 강화합니다.",
  },
  {
    name: "Long Stretch",
    nameKo: "롱 스트레치",
    category: "upper_body",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["shoulders", "chest", "triceps", "abs"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 플랭크 자세로 밀고 당기며 상체를 강화합니다.",
  },
  {
    name: "Up Stretch",
    nameKo: "업 스트레치",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["shoulders", "abs", "hamstrings"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 파이크 자세로 밀며 어깨와 코어를 강화합니다.",
  },
  {
    name: "Down Stretch",
    nameKo: "다운 스트레치",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["chest", "shoulders", "spine_extensors"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "리포머에서 가슴을 열며 밀어 상체와 자세를 강화합니다.",
  },
  {
    name: "Tendon Stretch",
    nameKo: "텐던 스트레치",
    category: "upper_body",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["shoulders", "triceps", "abs"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 팔로 지탱하고 뛰어내리는 고급 동작입니다.",
  },
  {
    name: "Tricep Press on Chair",
    nameKo: "체어 삼두근 프레스",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["triceps", "shoulders"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "체어 페달을 누르며 삼두근을 집중 강화합니다.",
  },
  {
    name: "Dips on Chair",
    nameKo: "체어 딥스",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["triceps", "shoulders", "chest"],
    contraindications: ["손목터널증후군", "어깨부상"],
    durationSeconds: 60,
    description: "체어에서 딥스하며 삼두근과 어깨를 강화합니다.",
  },
  {
    name: "Bicep Curl on Reformer",
    nameKo: "리포머 이두근 컬",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["biceps", "forearms"],
    contraindications: [],
    durationSeconds: 45,
    description: "리포머 스트랩으로 이두근을 강화합니다.",
  },
  {
    name: "Rowing Series",
    nameKo: "로잉 시리즈",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["lats", "rhomboids", "biceps", "abs"],
    contraindications: [],
    durationSeconds: 90,
    description: "리포머에서 다양한 로잉 동작으로 등과 팔을 강화합니다.",
  },
  {
    name: "Shoulder Press on Reformer",
    nameKo: "리포머 숄더 프레스",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["deltoids", "triceps", "trapezius"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "리포머에서 어깨를 밀어올리며 삼각근을 강화합니다.",
  },
  {
    name: "Lat Pull Down on Tower",
    nameKo: "타워 랫 풀다운",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "tower",
    muscleGroups: ["lats", "biceps", "rhomboids"],
    contraindications: [],
    durationSeconds: 60,
    description: "타워 스프링을 당기며 광배근을 강화합니다.",
  },
  {
    name: "Push Through Bar Overhead",
    nameKo: "푸시 스루 바 오버헤드",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "cadillac",
    muscleGroups: ["shoulders", "triceps", "lats"],
    contraindications: ["어깨부상"],
    durationSeconds: 60,
    description: "캐딜락 바를 머리 위로 밀며 어깨와 삼두근을 강화합니다.",
  },
  {
    name: "Arm Weight Boxing",
    nameKo: "암 웨이트 복싱",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["shoulders", "triceps", "abs"],
    contraindications: [],
    durationSeconds: 45,
    description: "가벼운 웨이트로 복싱 동작하며 어깨를 강화합니다.",
  },
  {
    name: "Arm Weight Bug",
    nameKo: "암 웨이트 벅",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["biceps", "shoulders"],
    contraindications: [],
    durationSeconds: 45,
    description: "가벼운 웨이트로 작은 원을 그리며 팔을 강화합니다.",
  },
  {
    name: "Arm Weight Zip Up",
    nameKo: "암 웨이트 지퍼",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["deltoids", "trapezius", "biceps"],
    contraindications: ["어깨부상"],
    durationSeconds: 45,
    description: "지퍼를 올리듯 팔을 당기며 어깨와 상부 등을 강화합니다.",
  },

  // ========================================
  // ===== BALANCE (25개) =====
  // ========================================
  {
    name: "Single Leg Balance on Chair",
    nameKo: "체어 싱글 레그 밸런스",
    category: "balance",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["glutes", "calves", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "필라테스 체어에서 한 발 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Bosu Ball Balance",
    nameKo: "보수볼 밸런스",
    category: "balance",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["calves", "abs", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "보수볼 위에서 균형을 잡으며 전신 안정성을 높입니다.",
  },
  {
    name: "Standing Balance Reformer",
    nameKo: "리포머 스탠딩 밸런스",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["calves", "glutes", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 서서 균형을 잡으며 안정성을 강화합니다.",
  },
  {
    name: "Quadruped Balance",
    nameKo: "네발 기기 밸런스",
    category: "balance",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "glutes", "spine_extensors"],
    contraindications: [],
    durationSeconds: 60,
    description: "네발 기기 자세에서 팔다리를 들어 균형을 잡습니다.",
  },
  // 추가 21개
  {
    name: "Tree on Reformer",
    nameKo: "리포머 트리",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "abs", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에 앉아 한 다리를 펴며 균형을 잡습니다.",
  },
  {
    name: "Standing Leg Pump on Chair",
    nameKo: "체어 스탠딩 레그 펌프",
    category: "balance",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 60,
    description: "체어에 서서 페달을 밟으며 균형과 하체를 강화합니다.",
  },
  {
    name: "Arabesque on Chair",
    nameKo: "체어 아라베스크",
    category: "balance",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["glutes", "hamstrings", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "체어에서 한 다리를 뒤로 들며 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Kneeling Side Arm",
    nameKo: "닐링 사이드 암",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["obliques", "shoulders", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "무릎을 꿇고 옆으로 팔 운동하며 균형을 잡습니다.",
  },
  {
    name: "Lunge on Reformer",
    nameKo: "리포머 런지",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["quads", "glutes", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 런지하며 균형과 하체 근력을 강화합니다.",
  },
  {
    name: "Star on Reformer",
    nameKo: "리포머 스타",
    category: "balance",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["obliques", "shoulders", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 별 자세로 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Standing on One Leg Chair",
    nameKo: "체어 한발 서기",
    category: "balance",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["calves", "glutes", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "체어에서 한 발로 서며 균형과 안정성을 강화합니다.",
  },
  {
    name: "Balance Control Front",
    nameKo: "밸런스 컨트롤 프론트",
    category: "balance",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["shoulders", "abs", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "플랭크 자세에서 한 다리를 들어 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Balance Control Back",
    nameKo: "밸런스 컨트롤 백",
    category: "balance",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["triceps", "abs", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "역 플랭크에서 한 다리를 들어 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Plank to Pike on Ball",
    nameKo: "볼 플랭크 투 파이크",
    category: "balance",
    difficulty: "advanced",
    equipment: "ball",
    muscleGroups: ["shoulders", "abs", "hip_flexors"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "짐볼 위에서 플랭크와 파이크를 반복하며 균형을 강화합니다.",
  },
  {
    name: "Kneeling on Reformer",
    nameKo: "리포머 닐링",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "glutes", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에 무릎 꿇고 균형을 잡으며 코어를 강화합니다.",
  },
  {
    name: "Bird Dog on Reformer",
    nameKo: "리포머 버드독",
    category: "balance",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "spine_extensors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 버드독을 수행하며 불안정면 균형을 강화합니다.",
  },
  {
    name: "Side Sit Up on Barrel",
    nameKo: "배럴 사이드 싯업",
    category: "balance",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["obliques", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "배럴에 옆으로 기대어 일어나며 균형과 복사근을 강화합니다.",
  },
  {
    name: "Standing Arm Series",
    nameKo: "스탠딩 암 시리즈",
    category: "balance",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["shoulders", "biceps", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "서서 밴드 팔 운동을 하며 균형과 상체를 동시에 강화합니다.",
  },
  {
    name: "Tandem Stance Balance",
    nameKo: "일렬 서기 밸런스",
    category: "balance",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["calves", "abs", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "발을 앞뒤 일렬로 놓고 균형을 잡는 기본 동작입니다.",
  },
  {
    name: "Single Leg Squat on Chair",
    nameKo: "체어 싱글 레그 스쿼트",
    category: "balance",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "abs"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어에서 한 발로 스쿼트하며 균형과 하체를 강화합니다.",
  },
  {
    name: "Standing Pike on Chair",
    nameKo: "체어 스탠딩 파이크",
    category: "balance",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["shoulders", "abs", "hamstrings"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "체어에서 파이크 자세로 균형을 잡는 고급 동작입니다.",
  },
  {
    name: "Ball Sit Balance",
    nameKo: "볼 앉기 밸런스",
    category: "balance",
    difficulty: "beginner",
    equipment: "ball",
    muscleGroups: ["abs", "hip_flexors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "짐볼에 앉아 균형을 잡으며 코어를 활성화합니다.",
  },
  {
    name: "Ball Kneeling",
    nameKo: "볼 무릎 서기",
    category: "balance",
    difficulty: "advanced",
    equipment: "ball",
    muscleGroups: ["abs", "glutes", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "짐볼 위에 무릎으로 서며 전신 균형을 도전합니다.",
  },
  {
    name: "Step Down on Chair",
    nameKo: "체어 스텝 다운",
    category: "balance",
    difficulty: "intermediate",
    equipment: "chair",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: ["무릎부상"],
    durationSeconds: 60,
    description: "체어에서 한 발로 내려가며 균형과 하체를 강화합니다.",
  },
  {
    name: "Torso Rotation on Ball",
    nameKo: "볼 몸통 회전",
    category: "balance",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["obliques", "abs", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "짐볼에 기대어 몸통을 회전하며 균형과 코어를 강화합니다.",
  },

  // ========================================
  // ===== BREATHING (20개) =====
  // ========================================
  {
    name: "Diaphragmatic Breathing",
    nameKo: "횡격막 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "pelvic_floor"],
    contraindications: [],
    durationSeconds: 60,
    description: "깊은 횡격막 호흡으로 몸과 마음을 안정시킵니다.",
  },
  {
    name: "Lateral Breathing",
    nameKo: "측면 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["intercostals", "diaphragm"],
    contraindications: [],
    durationSeconds: 60,
    description: "갈비뼈를 옆으로 확장하는 필라테스 기본 호흡법입니다.",
  },
  {
    name: "Percussive Breathing",
    nameKo: "타악 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "diaphragm"],
    contraindications: [],
    durationSeconds: 45,
    description: "짧고 강한 호흡으로 코어를 활성화합니다.",
  },
  // 추가 17개
  {
    name: "Posterior Lateral Breathing",
    nameKo: "후측방 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["intercostals", "diaphragm", "multifidus"],
    contraindications: [],
    durationSeconds: 60,
    description: "갈비뼈 뒤쪽으로 호흡을 확장하며 깊은 호흡을 연습합니다.",
  },
  {
    name: "Breath with Arm Raises",
    nameKo: "팔 올리기 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "shoulders", "intercostals"],
    contraindications: [],
    durationSeconds: 60,
    description: "팔을 올리며 호흡하여 흉곽 확장을 유도합니다.",
  },
  {
    name: "Seated Breathing",
    nameKo: "앉은 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals", "pelvic_floor"],
    contraindications: [],
    durationSeconds: 60,
    description: "앉은 자세에서 정확한 호흡 패턴을 연습합니다.",
  },
  {
    name: "Supine Breathing with Band",
    nameKo: "밴드 누운 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["intercostals", "diaphragm"],
    contraindications: [],
    durationSeconds: 60,
    description: "밴드를 갈비뼈에 감고 호흡하여 횡격막 확장을 느낍니다.",
  },
  {
    name: "Standing Breath Work",
    nameKo: "서서 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "서서 올바른 호흡 패턴을 연습합니다.",
  },
  {
    name: "Pelvic Floor Breathing",
    nameKo: "골반기저근 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["pelvic_floor", "diaphragm", "transverse_abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "호흡과 골반기저근 활성화를 연결하여 코어 기초를 다집니다.",
  },
  {
    name: "360 Degree Breathing",
    nameKo: "360도 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals", "transverse_abs", "multifidus"],
    contraindications: [],
    durationSeconds: 60,
    description: "갈비뼈를 전후좌우 모든 방향으로 확장하는 호흡법입니다.",
  },
  {
    name: "Exhale with Core Activation",
    nameKo: "코어 활성화 날숨",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["transverse_abs", "diaphragm", "pelvic_floor"],
    contraindications: [],
    durationSeconds: 60,
    description: "날숨 시 코어를 수축하여 호흡과 코어 연결을 강화합니다.",
  },
  {
    name: "Breath with Spine Articulation",
    nameKo: "척추 분절 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["diaphragm", "spine_extensors", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "호흡에 맞춰 척추를 분절하며 움직임과 호흡을 연결합니다.",
  },
  {
    name: "Breath with Ribcage Closure",
    nameKo: "흉곽 닫기 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["intercostals", "obliques", "diaphragm"],
    contraindications: [],
    durationSeconds: 60,
    description: "날숨 시 갈비뼈를 닫으며 흉곽 조절력을 높입니다.",
  },
  {
    name: "Forced Exhalation",
    nameKo: "강제 날숨",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "intercostals", "diaphragm"],
    contraindications: ["고혈압"],
    durationSeconds: 45,
    description: "강하게 내쉬며 복근과 횡격막의 협응을 강화합니다.",
  },
  {
    name: "Breath Coordination Reformer",
    nameKo: "리포머 호흡 코디네이션",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["abs", "diaphragm", "intercostals"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머 움직임에 호흡을 맞추며 호흡 패턴을 최적화합니다.",
  },
  {
    name: "Sighing Breath",
    nameKo: "한숨 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals"],
    contraindications: [],
    durationSeconds: 60,
    description: "깊이 들이쉬고 한숨처럼 내쉬며 긴장을 이완합니다.",
  },
  {
    name: "Box Breathing",
    nameKo: "박스 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals"],
    contraindications: [],
    durationSeconds: 60,
    description: "4초 들숨-4초 멈춤-4초 날숨-4초 멈춤의 규칙적 호흡법입니다.",
  },
  {
    name: "Breath with Pelvic Tilt",
    nameKo: "골반 기울임 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "abs", "pelvic_floor"],
    contraindications: [],
    durationSeconds: 60,
    description: "호흡에 맞춰 골반을 기울이며 호흡과 움직임을 연결합니다.",
  },
  {
    name: "Imprint and Release Breathing",
    nameKo: "임프린트 앤 릴리스 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["transverse_abs", "diaphragm", "multifidus"],
    contraindications: [],
    durationSeconds: 60,
    description: "호흡에 맞춰 허리를 바닥에 붙이고 떼며 코어를 활성화합니다.",
  },
  {
    name: "Sniffing Breath",
    nameKo: "스니핑 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["diaphragm", "intercostals", "abs"],
    contraindications: [],
    durationSeconds: 45,
    description: "짧은 들숨을 여러 번 나누어 흡입하며 횡격막을 활성화합니다.",
  },
];

async function seed() {
  console.log("Seeding exercise catalog...");
  console.log(`Total exercises to seed: ${exercises.length}`);

  // Count by category
  const categoryCounts: Record<string, number> = {};
  for (const ex of exercises) {
    categoryCounts[ex.category] = (categoryCounts[ex.category] || 0) + 1;
  }
  console.log("Category counts:", categoryCounts);

  // Delete existing data and insert fresh
  await db.delete(exerciseCatalog);
  console.log("Deleted existing exercise catalog data.");

  let inserted = 0;
  for (const exercise of exercises) {
    try {
      await db.insert(exerciseCatalog).values(exercise);
      inserted++;
    } catch (err) {
      console.error(`Failed to insert ${exercise.name}:`, err);
    }
  }

  console.log(`Successfully seeded ${inserted}/${exercises.length} exercises.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
