import "dotenv/config";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { exerciseCatalog } from "./schema";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

const client = postgres(databaseUrl);
const db = drizzle(client);

const exercises = [
  // ===== breathing =====
  {
    name: "Diaphragmatic Breathing",
    nameKo: "횡격막 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["diaphragm", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "깊은 횡격막 호흡으로 몸과 마음을 안정시킵니다.",
  },
  {
    name: "Lateral Breathing",
    nameKo: "측면 호흡",
    category: "breathing",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["intercostals", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "갈비뼈를 옆으로 확장하는 필라테스 기본 호흡법입니다.",
  },
  {
    name: "Percussive Breathing",
    nameKo: "타악 호흡",
    category: "breathing",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["core", "diaphragm"],
    contraindications: [],
    durationSeconds: 45,
    description: "짧고 강한 호흡으로 코어를 활성화합니다.",
  },

  // ===== stretching =====
  {
    name: "Cat-Cow Stretch",
    nameKo: "고양이-소 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "척추를 부드럽게 움직여 유연성을 향상시킵니다.",
  },
  {
    name: "Spine Stretch Forward",
    nameKo: "척추 전방 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine", "hamstrings"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 척추를 앞으로 둥글게 말아 스트레칭합니다.",
  },
  {
    name: "Mermaid Stretch",
    nameKo: "인어 스트레칭",
    category: "stretching",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "lats", "spine"],
    contraindications: ["측만증"],
    durationSeconds: 60,
    description: "옆으로 몸을 길게 늘여 측면 근육을 이완합니다.",
  },
  {
    name: "Hip Flexor Stretch",
    nameKo: "고관절 굴곡근 스트레칭",
    category: "stretching",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "quads"],
    contraindications: [],
    durationSeconds: 60,
    description: "고관절 앞쪽 근육을 늘여 유연성을 높입니다.",
  },
  {
    name: "Saw",
    nameKo: "쏘우",
    category: "stretching",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hamstrings", "obliques", "spine"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 회전하며 스트레칭하는 동작입니다.",
  },

  // ===== core =====
  {
    name: "The Hundred",
    nameKo: "헌드레드",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "core"],
    contraindications: ["목디스크"],
    durationSeconds: 120,
    description: "팔을 펌핑하며 코어를 활성화하는 필라테스 대표 동작입니다.",
  },
  {
    name: "Roll Up",
    nameKo: "롤업",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "spine"],
    contraindications: ["허리디스크"],
    durationSeconds: 90,
    description: "누운 상태에서 척추를 하나씩 들어올리며 일어나는 동작입니다.",
  },
  {
    name: "Single Leg Stretch",
    nameKo: "싱글 레그 스트레치",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "한쪽 다리를 번갈아 당기며 코어를 강화합니다.",
  },
  {
    name: "Double Leg Stretch",
    nameKo: "더블 레그 스트레치",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "core"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "양 팔다리를 동시에 뻗으며 코어 안정성을 높입니다.",
  },
  {
    name: "Criss-Cross",
    nameKo: "크리스크로스",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "abs"],
    contraindications: ["목디스크"],
    durationSeconds: 60,
    description: "상체를 회전하며 복사근을 강화합니다.",
  },
  {
    name: "Plank",
    nameKo: "플랭크",
    category: "core",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["core", "shoulders", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "전신의 코어 근육을 동시에 활성화하는 기본 동작입니다.",
  },
  {
    name: "Dead Bug",
    nameKo: "데드버그",
    category: "core",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "누운 상태에서 팔다리를 교차로 움직이며 코어를 안정화합니다.",
  },
  {
    name: "Teaser",
    nameKo: "티저",
    category: "core",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["abs", "hip_flexors", "spine"],
    contraindications: ["허리디스크", "목디스크"],
    durationSeconds: 90,
    description: "V자 균형을 잡으며 전신 코어를 강화하는 고급 동작입니다.",
  },
  {
    name: "Bicycle",
    nameKo: "바이시클",
    category: "core",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["abs", "obliques", "hip_flexors"],
    contraindications: [],
    durationSeconds: 60,
    description: "자전거 페달을 밟는 동작으로 복근 전체를 활성화합니다.",
  },

  // ===== flexibility =====
  {
    name: "Swan Dive",
    nameKo: "스완 다이브",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["back_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크", "척추분리증"],
    durationSeconds: 60,
    description: "엎드려 상체를 들어올리며 척추 신전 유연성을 높입니다.",
  },
  {
    name: "Swan Prep",
    nameKo: "스완 프렙",
    category: "flexibility",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["back_extensors", "core"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 가볍게 상체를 들어올리는 입문 동작입니다.",
  },
  {
    name: "Rolling Like a Ball",
    nameKo: "롤링 라이크 어 볼",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["spine", "abs"],
    contraindications: ["허리디스크", "골다공증"],
    durationSeconds: 60,
    description: "공처럼 구르며 척추 마사지 효과와 코어를 강화합니다.",
  },
  {
    name: "Open Leg Rocker",
    nameKo: "오픈 레그 로커",
    category: "flexibility",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["hamstrings", "abs", "spine"],
    contraindications: ["허리디스크", "골다공증"],
    durationSeconds: 60,
    description: "다리를 펴고 균형을 잡으며 구르는 고급 동작입니다.",
  },
  {
    name: "Spine Twist",
    nameKo: "스파인 트위스트",
    category: "flexibility",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "spine"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "앉은 자세에서 상체를 회전하여 척추 유연성을 높입니다.",
  },

  // ===== upper_body =====
  {
    name: "Push Up",
    nameKo: "푸시업",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["chest", "triceps", "shoulders", "core"],
    contraindications: ["손목터널증후군", "어깨충돌증후군"],
    durationSeconds: 60,
    description: "필라테스 스타일의 푸시업으로 상체와 코어를 함께 강화합니다.",
  },
  {
    name: "Arm Circles with Band",
    nameKo: "밴드 팔 원 그리기",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["shoulders", "arms"],
    contraindications: ["어깨충돌증후군"],
    durationSeconds: 45,
    description: "밴드 저항을 이용해 어깨 안정성을 높입니다.",
  },
  {
    name: "Chest Expansion",
    nameKo: "체스트 익스팬션",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["chest", "shoulders", "back"],
    contraindications: [],
    durationSeconds: 45,
    description: "가슴을 열고 어깨를 뒤로 당기는 자세 교정 운동입니다.",
  },
  {
    name: "Scapular Stabilization",
    nameKo: "견갑골 안정화",
    category: "upper_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["scapular_stabilizers", "rhomboids"],
    contraindications: [],
    durationSeconds: 45,
    description: "견갑골 주변 근육을 강화하여 어깨 안정성을 높입니다.",
  },
  {
    name: "Tricep Press on Reformer",
    nameKo: "리포머 삼두근 프레스",
    category: "upper_body",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["triceps", "core"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 삼두근을 집중 강화하는 운동입니다.",
  },

  // ===== lower_body =====
  {
    name: "Leg Circle",
    nameKo: "레그 서클",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_flexors", "quads", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "누워서 다리로 원을 그리며 고관절을 강화합니다.",
  },
  {
    name: "Side Leg Series",
    nameKo: "사이드 레그 시리즈",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["hip_abductors", "glutes", "core"],
    contraindications: [],
    durationSeconds: 90,
    description: "옆으로 누워 다리를 다양한 방향으로 움직이며 고관절을 강화합니다.",
  },
  {
    name: "Bridge",
    nameKo: "브릿지",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "엉덩이를 들어올리며 둔근과 코어를 강화합니다.",
  },
  {
    name: "Single Leg Bridge",
    nameKo: "싱글 레그 브릿지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "core"],
    contraindications: [],
    durationSeconds: 60,
    description: "한 다리로 브릿지를 수행하여 불균형을 교정합니다.",
  },
  {
    name: "Footwork on Reformer",
    nameKo: "리포머 풋워크",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "reformer",
    muscleGroups: ["quads", "glutes", "calves"],
    contraindications: [],
    durationSeconds: 90,
    description: "리포머에서 다리 근력과 정렬을 개선합니다.",
  },
  {
    name: "Clamshell",
    nameKo: "클램셸",
    category: "lower_body",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["hip_abductors", "glutes"],
    contraindications: [],
    durationSeconds: 45,
    description: "옆으로 누워 무릎을 열고 닫으며 둔근을 활성화합니다.",
  },
  {
    name: "Lunge with Ball",
    nameKo: "볼 런지",
    category: "lower_body",
    difficulty: "intermediate",
    equipment: "ball",
    muscleGroups: ["quads", "glutes", "core"],
    contraindications: ["무릎연골손상"],
    durationSeconds: 60,
    description: "볼을 이용한 런지로 하체 근력과 균형을 향상합니다.",
  },

  // ===== balance =====
  {
    name: "Standing Balance",
    nameKo: "스탠딩 밸런스",
    category: "balance",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["core", "ankles", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "한 발로 서서 균형을 잡으며 전신 안정성을 높입니다.",
  },
  {
    name: "Bird Dog",
    nameKo: "버드독",
    category: "balance",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["core", "back_extensors", "glutes"],
    contraindications: [],
    durationSeconds: 60,
    description: "네발 기기 자세에서 반대쪽 팔다리를 들어 균형을 잡습니다.",
  },
  {
    name: "Swimming",
    nameKo: "스위밍",
    category: "balance",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["back_extensors", "glutes", "shoulders"],
    contraindications: ["허리디스크"],
    durationSeconds: 60,
    description: "엎드려 팔다리를 교차로 들어올리며 등 근육과 균형을 강화합니다.",
  },
  {
    name: "Single Leg Balance on Chair",
    nameKo: "체어 싱글 레그 밸런스",
    category: "balance",
    difficulty: "advanced",
    equipment: "chair",
    muscleGroups: ["core", "glutes", "ankles"],
    contraindications: [],
    durationSeconds: 60,
    description: "필라테스 체어에서 한 발 균형을 잡는 고급 동작입니다.",
  },

  // ===== posture =====
  {
    name: "Chest Lift",
    nameKo: "체스트 리프트",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["abs", "neck_flexors"],
    contraindications: ["목디스크"],
    durationSeconds: 45,
    description: "누워서 상체를 살짝 들어올리며 복근을 활성화합니다.",
  },
  {
    name: "Shoulder Bridge",
    nameKo: "숄더 브릿지",
    category: "posture",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["glutes", "hamstrings", "spine"],
    contraindications: [],
    durationSeconds: 60,
    description: "골반을 들어올리며 척추 정렬과 둔근을 강화합니다.",
  },
  {
    name: "Wall Roll Down",
    nameKo: "월 롤다운",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["spine", "hamstrings", "abs"],
    contraindications: [],
    durationSeconds: 60,
    description: "벽에 기대어 척추를 하나씩 말아내리며 자세를 교정합니다.",
  },
  {
    name: "Pelvic Curl",
    nameKo: "펠빅 컬",
    category: "posture",
    difficulty: "beginner",
    equipment: "mat",
    muscleGroups: ["core", "glutes", "spine"],
    contraindications: [],
    durationSeconds: 60,
    description: "골반을 천천히 말아올리며 척추 분절 움직임을 연습합니다.",
  },
  {
    name: "Thoracic Extension on Barrel",
    nameKo: "배럴 흉추 신전",
    category: "posture",
    difficulty: "intermediate",
    equipment: "barrel",
    muscleGroups: ["thoracic_spine", "shoulders"],
    contraindications: ["흉추후만증"],
    durationSeconds: 60,
    description: "배럴 위에서 흉추를 부드럽게 신전하여 자세를 개선합니다.",
  },

  // ===== strength =====
  {
    name: "Leg Pull Front",
    nameKo: "레그 풀 프론트",
    category: "strength",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["core", "shoulders", "glutes"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "플랭크 자세에서 한 다리를 들어올리는 전신 강화 동작입니다.",
  },
  {
    name: "Leg Pull Back",
    nameKo: "레그 풀 백",
    category: "strength",
    difficulty: "advanced",
    equipment: "mat",
    muscleGroups: ["triceps", "core", "hamstrings"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "역 플랭크에서 한 다리를 들어올리는 고급 동작입니다.",
  },
  {
    name: "Side Plank",
    nameKo: "사이드 플랭크",
    category: "strength",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "shoulders", "core"],
    contraindications: ["손목터널증후군", "어깨충돌증후군"],
    durationSeconds: 45,
    description: "옆으로 몸을 지탱하며 측면 코어를 강화합니다.",
  },
  {
    name: "Long Stretch on Reformer",
    nameKo: "리포머 롱 스트레치",
    category: "strength",
    difficulty: "advanced",
    equipment: "reformer",
    muscleGroups: ["core", "shoulders", "chest"],
    contraindications: ["손목터널증후군"],
    durationSeconds: 60,
    description: "리포머에서 플랭크 자세로 전신 근력을 강화합니다.",
  },
  {
    name: "Squat with Band",
    nameKo: "밴드 스쿼트",
    category: "strength",
    difficulty: "beginner",
    equipment: "band",
    muscleGroups: ["quads", "glutes", "core"],
    contraindications: ["무릎연골손상"],
    durationSeconds: 60,
    description: "밴드 저항을 추가한 스쿼트로 하체를 강화합니다.",
  },
  {
    name: "Kneeling Side Kick",
    nameKo: "닐링 사이드 킥",
    category: "strength",
    difficulty: "intermediate",
    equipment: "mat",
    muscleGroups: ["obliques", "glutes", "hip_abductors"],
    contraindications: [],
    durationSeconds: 60,
    description: "무릎을 꿇고 옆으로 다리를 차며 균형과 근력을 강화합니다.",
  },
  {
    name: "Elephant on Reformer",
    nameKo: "리포머 엘리펀트",
    category: "strength",
    difficulty: "intermediate",
    equipment: "reformer",
    muscleGroups: ["hamstrings", "core", "shoulders"],
    contraindications: [],
    durationSeconds: 60,
    description: "리포머에서 파이크 자세로 햄스트링과 코어를 강화합니다.",
  },
];

async function seed() {
  console.log("Seeding exercise catalog...");

  for (const exercise of exercises) {
    try {
      await db
        .insert(exerciseCatalog)
        .values(exercise)
        .onConflictDoNothing({ target: exerciseCatalog.name });
    } catch (err) {
      console.error(`Failed to insert ${exercise.name}:`, err);
    }
  }

  console.log(`Seeded ${exercises.length} exercises.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
