// ===== API 공통 =====

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: ApiError;
}

export interface ApiError {
  code: string;
  message: string;
  statusCode: number;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// ===== 사용자/인증 =====

export type UserRole = "instructor" | "member";

export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  pushToken?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AuthTokens {
  accessToken: string;
  refreshToken?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  role: UserRole;
}

// ===== 인증 응답 =====

export interface AuthResponse {
  user: User;
  accessToken: string;
  refreshToken: string;
}

// ===== 회원 =====

export type FitnessLevel = "beginner" | "intermediate" | "advanced";

export interface BodyCondition {
  type: string;
  area: string;
  severity: "mild" | "moderate" | "severe";
  notes?: string;
}

export interface ExercisePreferences {
  preferredEquipment: string[];
  targetMuscles: string[];
  avoidExercises: string[];
  goals: string[];
  sessionDurationMinutes: number;
  isPrenatal?: boolean;
  isPostnatal?: boolean;
}

export interface Member {
  id: string;
  userId: string;
  name: string;
  phone?: string;
  dateOfBirth?: string;
  bodyConditions: BodyCondition[];
  exercisePreferences: ExercisePreferences;
  fitnessLevel: FitnessLevel;
  notes?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 컨디션 분석 =====

export type Mood = "HAPPY" | "CALM" | "SAD" | "STRESSED" | "TIRED";
export type SleepQuality = "GOOD" | "FAIR" | "POOR";
export type SwellingLevel = "NONE" | "MILD" | "MODERATE";

export interface ConditionAnalysis {
  energy: number;
  mood: Mood;
  stress: number;
  summary: string;
  sleepQuality?: SleepQuality;
  facialTension?: {
    forehead: boolean;
    jaw: boolean;
    asymmetry: boolean;
  };
  swelling?: SwellingLevel;
  skinCondition?: {
    pale: boolean;
    flushed: boolean;
  };
  confidence: Record<string, number>;
}

// ===== 세션 =====

export interface Session {
  id: string;
  memberId: string;
  date: string;
  conditionAiRaw?: ConditionAnalysis;
  conditionFinal?: ConditionAnalysis;
  memberNote?: string;
  requestedCategories?: string[];
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 운동 시퀀스 =====

export interface Exercise {
  catalogId: string;
  name: string;
  category: string;
  duration?: number;
  reps?: number;
  sets?: number;
  notes?: string;
}

export interface ExerciseInSequence {
  catalogId: string;
  name: string;
  nameKo: string;
  category: string;
  equipment: string;
  sets: number;
  reps?: number;
  durationSeconds: number;
  order: number;
  reason: string;
}

export interface ExerciseSequence {
  id: string;
  sessionId: string;
  memberId: string;
  exercises: ExerciseInSequence[];
  totalDurationMinutes: number;
  difficulty: string;
  focusAreas: string[];
  sequenceNote?: string;
  wasModified: boolean;
  createdAt: string;
}

/** @deprecated Use ExerciseSequence instead */
export interface ExerciseSequenceLegacy {
  id: string;
  sessionId: string;
  exercises: Exercise[];
  aiRationale?: string;
  instructorNotes?: string;
  reviewedByInstructor: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 주간 스케줄 =====

export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface WeeklySchedule {
  id: string;
  instructorId: string;
  memberId: string;
  memberName?: string;
  dayOfWeek: DayOfWeek;
  startTime: string;
  endTime: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== AI 컨디션 분석 (상세) =====

export interface ConditionAnalysisDetailed {
  energy: { level: number; confidence: number };
  mood: { value: Mood; confidence: number };
  stress: { level: number; confidence: number };
  sleep: { quality: SleepQuality; confidence: number };
  facialTension: {
    forehead: { level: number; confidence: number };
    jaw: { level: number; confidence: number };
    asymmetry: { value: string; confidence: number };
  };
  swelling: { level: SwellingLevel; confidence: number };
  summary: string;
  exerciseNote?: string;
}

// ===== 컨디션 최종 확정 =====

export interface ConditionFinal {
  energy: number;
  mood: Mood;
  stress: number;
  sleep: SleepQuality;
  summary: string;
}

// ===== 오늘 스케줄 항목 =====

export interface TodayScheduleItem {
  memberId: string;
  memberName: string;
  startTime: string;
  conditionChecked: boolean;
  sequenceGenerated: boolean;
}

// ===== 운동 카테고리 =====

export type ExerciseCategory =
  | "CORE"
  | "FLEXIBILITY"
  | "UPPER_BODY"
  | "LOWER_BODY"
  | "BALANCE"
  | "STRETCHING"
  | "BREATHING"
  | "POSTURE"
  | "STRENGTH"
  | "REHABILITATION"
  | "PRENATAL"
  | "POSTNATAL"
  | "CARDIO_ENDURANCE"
  | "COORDINATION"
  | "RELAXATION_RECOVERY"
  | "SPINE_MOBILITY"
  | "HIP_PELVIS"
  | "FOOT_ANKLE"
  | "FUNCTIONAL"
  | "FULL_BODY"
  | "LATERAL_MOVEMENT"
  | "PELVIC_FLOOR";

// ===== 강사 대시보드 =====

export interface DashboardSession {
  memberId: string;
  memberName: string;
  startTime: string;
  conditionChecked: boolean;
  conditionSummary?: string;
  sequenceGenerated: boolean;
  sequenceId?: string;
  sessionId?: string;
  difficulty?: string;
  exerciseCount?: number;
  totalDurationMinutes?: number;
  wasModified?: boolean;
}

export interface DashboardData {
  date: string;
  totalMembers: number;
  conditionChecked: number;
  sequenceGenerated: number;
  sessions: DashboardSession[];
}

// ===== 운동 카탈로그 =====

export interface ExerciseCatalogItem {
  id: string;
  name: string;
  nameKo: string;
  category: string;
  equipment: string;
  difficulty: string;
  description?: string;
  descriptionKo?: string;
}
