// ===== API 공통 =====

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: ApiError;
}

export interface ApiError {
  code: string;
  message: string;
  statusCode: number;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// ===== 사용자/인증 =====

export type UserRole = "instructor" | "member";

export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  pushToken?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AuthTokens {
  accessToken: string;
  refreshToken?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  role: UserRole;
}

// ===== 인증 응답 =====

export interface AuthResponse {
  user: User;
  accessToken: string;
  refreshToken: string;
}

// ===== 회원 =====

export type FitnessLevel = "beginner" | "intermediate" | "advanced";

export interface BodyCondition {
  type: string;
  area: string;
  severity: "mild" | "moderate" | "severe";
  notes?: string;
}

export interface ExercisePreferences {
  preferredEquipment: string[];
  avoidExercises: string[];
  goals: string[];
  sessionDurationMinutes: number;
}

export interface Member {
  id: string;
  userId: string;
  name: string;
  phone?: string;
  dateOfBirth?: string;
  bodyConditions: BodyCondition[];
  exercisePreferences: ExercisePreferences;
  fitnessLevel: FitnessLevel;
  notes?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 컨디션 분석 =====

export type Mood = "HAPPY" | "CALM" | "SAD" | "STRESSED" | "TIRED";
export type SleepQuality = "GOOD" | "FAIR" | "POOR";
export type SwellingLevel = "NONE" | "MILD" | "MODERATE";

export interface ConditionAnalysis {
  energy: number;
  mood: Mood;
  stress: number;
  summary: string;
  sleepQuality?: SleepQuality;
  facialTension?: {
    forehead: boolean;
    jaw: boolean;
    asymmetry: boolean;
  };
  swelling?: SwellingLevel;
  skinCondition?: {
    pale: boolean;
    flushed: boolean;
  };
  confidence: Record<string, number>;
}

// ===== 세션 =====

export interface Session {
  id: string;
  memberId: string;
  date: string;
  conditionAiRaw?: ConditionAnalysis;
  conditionFinal?: ConditionAnalysis;
  memberNote?: string;
  requestedCategories?: string[];
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 운동 시퀀스 =====

export interface Exercise {
  catalogId: string;
  name: string;
  category: string;
  duration?: number;
  reps?: number;
  sets?: number;
  notes?: string;
}

export interface ExerciseSequence {
  id: string;
  sessionId: string;
  exercises: Exercise[];
  aiRationale?: string;
  instructorNotes?: string;
  reviewedByInstructor: boolean;
  createdAt: string;
  updatedAt: string;
}

// ===== 주간 스케줄 =====

export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface WeeklySchedule {
  id: string;
  instructorId: string;
  memberId: string;
  dayOfWeek: DayOfWeek;
  startTime: string;
  endTime: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
